import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <Image alt="banner" src='/banner-image.jpeg' width= {200} height = {200}/>
        <p className={styles.description}>
          A blog for hunting coders from coder.
        </p>

        <div>
          <h2>Latest Blogs</h2>
          <ul className={styles.blogposts}>
            <li>
              <h3 className={styles.blogpost}>
                How to learn Javascript in 2022?
              </h3>
              <p>Javascript is a language used to build logic for webapps</p>
            </li>
            <li>
              <h3 className={styles.blogpost}>
                How to learn Javascript in 2022?
              </h3>
              <p>Javascript is a language used to build logic for webapps</p>
            </li>
            <li>
              <h3 className={styles.blogpost}>
                How to learn Javascript in 2022?
              </h3>
              <p>Javascript is a language used to build logic for webapps</p>
            </li>
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
